### ISSUE TITLE
PreviousHash is always ''

### ISSUE THREAD

**Issue by AntonD69** [SavjeeTutorials/SavjeeCoin#1]
I am rewriting the code into c#, so I can see for myself how it works ... and it seems to me that previousHash will always be '' (empty) in your example.

I have not run the code, so i might be reading it wrong.

Line 56 of main.js has this :
savjeeCoin.addBlock(new Block(1, "20/07/2017", { amount: 4 }));
The previousHash should be passed in from my understanding.

BTW. Brilliant video and explenation!

**Comment by Savjee** [comment]
The `addBlock()` method sets the previous hash.
This happens [here](https://github.com/SavjeeTutorials/SavjeeCoin/blob/master/src/main.js#L32)

**Comment by AntonD69** [comment]
Oops. You are 100% correct!
Thanks for the correction :)
