### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Norfeldt** [SavjeeTutorials/SavjeeCoin#10]
Would you be interested in putting a license on this repo? 

https://choosealicense.com/

**Comment by Savjee** [comment]
Oops! Completely forgot about license. Added MIT!

**Comment by Norfeldt** [comment]
Thank you very much.

To my knowledge is not a must to add a license, it's just to avoid people asking every time they wish to use it - which they are obligated to do. But I'm no expert.

It's a great code example. I really like it and it made some of my puzzles in understanding block chain click right in.
