### ISSUE TITLE
Reading data from a block

### ISSUE THREAD

**Issue by afuggini** [SavjeeTutorials/SavjeeCoin#4]
Hi @Savjee, great tutorial! I learned a lot about how blockchain works as you speak my language (javascript) ;)

Question, what would it take in your example to decrypt/read the data from a specific block?

Thanks!

**Comment by Savjee** [comment]
The entire blockchain is completely readable by anyone. There is no encryption to prevent people from reading data of a specific block.

**Comment by Savjee** [comment]
Closed for inactivity
