### ISSUE TITLE
Missing previous block hash? 

### ISSUE THREAD

**Issue by Jaked222** [SavjeeTutorials/SavjeeCoin#5]
Hello Savjee,

Correct me if I'm wrong, but in the third version of this code, shouldn't we add the latest block's hash when creating a new block in minePendingTransactions. Doesn't this ensure the integrity of our chain, were someone to try and alter a block?

for example:

```
  minePendingTransactions(miningRewardAddress) {
	let block = new Block(Date.now(), this.pendingTransactions, this.getLatestBlock().hash);
	block.mineBlock(this.difficulty);

	this.chain.push(block);
		
	this.pendingTransactions = [
		new Transaction(null, miningRewardAddress, this.miningReward)
	];
  }
```

also one small matter of cleanup, we no longer need to include this.index in the calculateHash function.

Thanks for the tutorials! They have definitely helped me to better understand what a blockchain is.

**Comment by Savjee** [comment]
You're absolutely right! What an oversight on my end!

I fixed those issue's in 9ebadadde33ebe5ac7b2e70981595a453dd1939c and 552d7ce2d65ab6c489ef48ebb89c5e6ac77a8960

Thanks a lot!
