### ISSUE TITLE
update code to newest concepts

### ISSUE THREAD

**Issue by belun** [SavjeeTutorials/SavjeeCoin#6]
https://github.com/SavjeeTutorials/SavjeeCoin/blob/552d7ce2d65ab6c489ef48ebb89c5e6ac77a8960/src/main-v3.js#L21
you are hashing the old "data" field, instead of the transactions field ( quite a big deal, since you have compromised your chain)

https://github.com/SavjeeTutorials/SavjeeCoin/blob/552d7ce2d65ab6c489ef48ebb89c5e6ac77a8960/src/main-v3.js#L44
also, the genesis block is initialized badly ( not so big deal )

( maybe make some unit tests next tutorial :D )

**Comment by Savjee** [comment]
Thanks! Jeez I really messed up!

The hashing is fixed in 4c351df36c778a41b0c88de9c1ea58369f0dbe8d
And the Genesis block has been cleaned up in 9a3ca7b79450e4e423eb214831530c9c73cc75d7

Thanks for reporting this!
