### ISSUE TITLE
Doubt: What is transaction in the block.

### ISSUE THREAD

**Issue by Sourabh-Pandit** [SavjeeTutorials/SavjeeCoin#7]
First of all, I would really like to thanks to make me understand the concept of Blockchain...

Now doubt :-
Will the transaction in the block be a list of transactions or a block will have a single transaction.. From your code it seems to be the list...

Thanks
SP

**Comment by Savjee** [comment]
In my first version a block could just contain 1 transaction.
The last version however switched to supporting multiple transactions per block (just like most other blockchain implementations)

I closed this issue because it's a question. Feel free to post follow up questions here.

**Comment by aaawhz** [comment]
it is simple , like deferred erea of git;

**Comment by aaawhz** [comment]
你可以多次修改文件 add到暂缓区 ,  然后一次性commit
