### ISSUE TITLE
Running node getting SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by marklovett** [SavjeeTutorials/SavjeeCoin#8]
When I run node main.js, at 8:30 in the video, at the first console log, I get the below Syntax error.

I created a plugin in my wordpress installation called my-blockchain, put your savjeecoin code in my-blockchain/js/main.js and called the main.js file in my plugin php file:   require 'js/main.js';

Help!

Marks-MacBook-Pro:js marklovett$ npm -v
5.6.0
Marks-MacBook-Pro:js marklovett$ node -v
v8.10.0
Marks-MacBook-Pro:js marklovett$ npm outdated
Package    Current  Wanted   Latest  Location
crypto-js    3.1.8   3.1.8  3.1.9-1
Marks-MacBook-Pro:js marklovett$ node main.js
/Users/marklovett/test-project/wordpress/wp-content/plugins/my-blockchain/js/main.js:65
let savjeeCoin = new Blockchain();
    ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3

**Comment by Savjee** [comment]
Hmm that's weird. Did you change anything in the `main.js` file?

**Comment by marklovett** [comment]
Thanks much for responding Xavier.

I think the only change was commenting out some unused code.

I tried to attach it to this email but gmail blocked it.

Mark Lovett

Mark Lovett Web Design <https://www.marklovettdesign.com/>
Creative Design | WordPress Expert | SEO Pro
Full Web Agency Services Freelance Rates
Site:       marklovettdesign.com <https://www.marklovettdesign.com/>
Email:    info@marklovettdesign.com
Phone:  301-802-2228 <(301)%20802-2228>
__________________________
Digital Marketing Service
SEOgld.com <http://seogld.com/>
__________________________
Portrait Photography
BethesdaHeadshots.com <https://www.bethesdaheadshots.com/>
MarkLovettPhotography.com <https://www.marklovettphotography.com/>
__________________________
Portrait Painting
MarkLovettStudio.com <https://www.marklovettstudio.com/>

**Comment by Savjee** [comment]
I can't help you without taking a look at your actual modifications.
Just copy-paste it into GitHub ;)

**Comment by marklovett** [comment]
Will do Xavier. Thank you!

Mark Lovett

Mark Lovett Web Design <https://www.marklovettdesign.com/>
Creative Design | WordPress Expert | SEO | Crypto
Full Web Agency Services Freelance Rates
Site:       marklovettdesign.com <https://www.marklovettdesign.com/>
Email:    info@marklovettdesign.com
Phone:  301-802-2228 <(301)%20802-2228>
__________________________
Digital Marketing Service
SEOgld.com <http://seogld.com/>
__________________________
Portrait Photography
BethesdaHeadshots.com <https://www.bethesdaheadshots.com/>
MarkLovettPhotography.com <https://www.marklovettphotography.com/>
__________________________
Portrait Painting
MarkLovettStudio.com <https://www.marklovettstudio.com/>

**Comment by marklovett** [comment]
Xavier,

Here's a link to my gist with the main.js and my plugin php file.

https://gist.github.com/marklovett/acab5e5408c7b200acdd768553b5a0c2

Thanks,
Mark

**Comment by Savjee** [comment]
You commented out the curly brace `}` on line 61: https://gist.github.com/marklovett/acab5e5408c7b200acdd768553b5a0c2#file-main-js-L61

That's causing the issue ;)

Because this isn't really a bug I'm closing this issue. You can however keep adding comments & I can still respond. Hope it helps!

**Comment by marklovett** [comment]
So sorry for the headache. Thanks so much Xavier! I'll give it a try now.

Mark Lovett

Mark Lovett Web Design <https://www.marklovettdesign.com/>
Creative Design | WordPress Expert | SEO | Crypto
Full Web Agency Services Freelance Rates
Site:       marklovettdesign.com <https://www.marklovettdesign.com/>
Email:    info@marklovettdesign.com
Phone:  301-802-2228 <(301)%20802-2228>
__________________________
Digital Marketing Service
SEOgld.com <http://seogld.com/>
__________________________
Portrait Photography
BethesdaHeadshots.com <https://www.bethesdaheadshots.com/>
MarkLovettPhotography.com <https://www.marklovettphotography.com/>
__________________________
Portrait Painting
MarkLovettStudio.com <https://www.marklovettstudio.com/>
